comment
todo
	^ '"TO DO ITEMS
- clean up dead code (current)
- check extensions made in previous package 
- merge to get back the ancestors
- check ScriptInterpreter?? 
	Do we need to create a class for a script
	How do we store a execution component:  [ ] and list of them [ ]
	for now we can only manipulate scripts outside the image. 

- refresh the readme
- make sure we can pass a script
- remove dependencies on fileman

- support for #! notation (done)
- installer for #! script runner

- filename or rio for file
- debug mode for scripts (escape to image)
- passing arguments to scripts
- pipes and filters (stdin and stdout)
- redirecting Smalltalk errors to stderr
- evaluating external Unix commands (cf. backtick commands)
- multi-=platform support (installers?)
- environment to develop and debug scripts (extend class browser?)
- demo scripts
- tutorial"'