comment
todo
	^ '"TO DO ITEMS
- clean up dead code
- support for #! notation
- installer for #! script runner
- passing arguments to scripts
- pipes and filters (stdin and stdout)
- redirecting Smalltalk errors to stderr
- evaluating external Unix commands (cf. backtick commands)
- multi-=platform support (installers?)
- debug mode for scripts (escape to image)
- mechanism to specify required packages for scripts
- local cache for required packages
- environment to develop and debug scripts (extend class browser?)
- demo scripts
- tutorial"'