as yet unclassified
colorizeMapSolarized
	^ {
		$Y -> (Ansi sgr: '38;5;3' sgr: '48;5;3').
		$O -> (Ansi sgr: '38;5;9' sgr: '48;5;9').
		$R -> (Ansi sgr: '38;5;1' sgr: '48;5;1').
		$M -> (Ansi sgr: '38;5;5' sgr: '48;5;5').
		$P -> (Ansi sgr: '38;5;13' sgr: '48;5;13').
		$B -> (Ansi sgr: '38;5;4' sgr: '48;5;4').
		$C -> (Ansi sgr: '38;5;6' sgr: '48;5;6').
		$G -> (Ansi sgr: '38;5;2' sgr: '48;5;2').
	}